[WIP] Improve Bsplines functions performance
rapidsai/cusignal pull request #236
Opened 2020-09-22 18:11 UTC by z-ryan1

Closes #231 

This PR improves performance for all bsplines functions.

2020-09-22 18:11 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-09-22 18:11 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-10-01 19:51 UTC, mnicely commented
> After talking with Matt we found that the helper function `_quadratic_coeff` is dead code and should be removed.
> 
> We also found that `cspline1d` uses both `_cubic_smooth_coeff` and `_cubic_coeff` which have data dependencies that should not be done on GPU version (see: line 187, 190, 202, 206 in [bsplines.py](https://github.com/rapidsai/cusignal/blob/ce096deddf61b527b54172adf3838d997f27c3b4/python/cusignal/bsplines/bsplines.py))

@awthomp How do you feel about this?

2020-10-01 20:17 UTC, awthomp commented
> > After talking with Matt we found that the helper function `_quadratic_coeff` is dead code and should be removed.
> > We also found that `cspline1d` uses both `_cubic_smooth_coeff` and `_cubic_coeff` which have data dependencies that should not be done on GPU version (see: line 187, 190, 202, 206 in [bsplines.py](https://github.com/rapidsai/cusignal/blob/ce096deddf61b527b54172adf3838d997f27c3b4/python/cusignal/bsplines/bsplines.py))
> 
> @awthomp How do you feel about this?

I'd keep it slow and on the GPU, within CuPy. If someone decides to use this function, ideally their E2E performance will make up for the sub-optimal GPU speed here.

2020-10-01 20:25 UTC, awthomp commented
Spoke with @mnicely offline, and I took a look back at my original implementation notes. I have that `cspline1d` is a 'serial algorithm and revisit it'. I'm okay with removing it from the library, similarly to what we did with `lfilter`.

2020-10-01 20:26 UTC, awthomp approved these changes

2020-10-01 20:27 UTC, mnicely commented
@z-ryan1 Please remove the dead and serial code.

2020-10-01 20:29 UTC, mnicely requested changes

2020-10-01 20:29 UTC, mnicely commented on python/cusignal/bsplines/bsplines.py
>  def _coeff_smooth(lam):
remove

2020-10-01 20:29 UTC, mnicely commented on python/cusignal/bsplines/bsplines.py
>  def _hc(k, cs, rho, omega):
remove

2020-10-01 20:29 UTC, mnicely commented on python/cusignal/bsplines/bsplines.py
>  def _hs(k, cs, rho, omega):
remove

2020-10-01 20:29 UTC, mnicely commented on python/cusignal/bsplines/bsplines.py
>  def _cubic_smooth_coeff(signal, lamb):
remove

2020-10-01 20:29 UTC, mnicely commented on python/cusignal/bsplines/bsplines.py
>  def _cubic_coeff(signal):
remove

2020-10-01 20:29 UTC, mnicely commented on python/cusignal/bsplines/bsplines.py
> +# def _quadratic_coeff(signal):
remove

2020-10-01 20:29 UTC, mnicely commented on python/cusignal/bsplines/bsplines.py
>  def cspline1d(signal, lamb=0.0):
remove

2020-10-01 20:51 UTC, mnicely commented
@awthomp @BradReesWork 
Do we wanna push this to 16 or 17?

2020-10-02 01:25 UTC, mnicely approved these changes

2020-10-02 01:25 UTC, merged