Update conda build files
rapidsai/cusignal pull request #237
Opened 2020-09-22 21:39 UTC by ajschmidt8

This PR updates cusignal's conda recipe `build.sh` file to use the `build.sh` file in the project's root directory. This fixes an issue where the `fatbin` files were not being generated for conda package uploads.

I also updated `conda/recipes/cusignal/meta.yaml` to use `path` instead of `git_url`, but I'm happy to revert this if requested. The differences are outlined in the excerpt below from the conda docs ([src](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#source-from-a-local-path)):

> "If the local path is a git or svn repository, you get the corresponding environment variables defined in your build environment. The only practical difference between git_url or hg_url and path as source arguments is that git_url and hg_url would be clones of a repository, while path would be a copy of the repository. **Using path allows you to build packages with unstaged and uncommitted changes in the working directory. git_url can build only up to the latest commit.**"

In essence, I couldn't test these changes locally when using `git_url` since it kept cloning the latest commit for the `conda build` process instead of using my working directory.

2020-09-22 21:39 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-09-23 00:06 UTC, ajschmidt8 commented
rerun tests

2020-09-23 14:41 UTC, raydouglass requested changes

2020-09-23 14:41 UTC, raydouglass commented on conda/recipes/cusignal/meta.yaml
> +  path: ../../..
What was the reason for this change? I think we use `git_url` everywhere else.

2020-09-23 16:40 UTC, raydouglass approved these changes

2020-09-23 16:58 UTC, merged