[WIP] Enhance FIR filter methods.
rapidsai/cusignal pull request #287
Opened 2020-11-25 19:06 UTC by luigifcruz

This pull-request implements the following:
- Initial conditions for the `firfilter` method.
- Zero-phase shift method called `firfilter2` (based on `scipy.signal.filtfilt`)
- FIR filter design tool `firwin2` (based on `scipy.signal.firwin2`)
- Initial conditions constructor `firfilter_zi`.
- Bindings for `lfilter` and `lfilter_zi` with `NotImplementedError` for IIR coefficients.
- Ignore `*.fatbin` files.

#### Dependencies:
This pull-request depends on the `cupy.apply_along_axis` method that is schedule to be released in version `9.0.0`. Users can test this PR by installing `cupy==9.0.0a1` from PyPi.

#### Todo List:
- [ ] Implement tests for the new methods.
- [ ] Wait for `cupy==9.0.0` release.

2020-11-25 19:07 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-11-25 19:07 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-11-25 19:17 UTC, awthomp commented
Thanks for the PR, @luigifcruz. I love the idea and will get a bit more time to dive into your work after Thanksgiving. Expect more input around Nov 30th.

2020-11-25 19:17 UTC, awthomp commented
ok to test

2020-11-25 21:19 UTC, BradReesWork commented
ok to test

2020-11-25 21:19 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-11-25 21:20 UTC, BradReesWork commented
add to allowlist

2020-11-25 21:20 UTC, BradReesWork commented
rerun tests

2020-12-02 14:02 UTC, awthomp commented
Hey @luigifcruz -- there are some coding style changes requested by CI before tests run. You can view them [here:]( https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fcusignal%2Fprb%2Fcusignal-style/detail/cusignal-style/689/pipeline)

```
>>>> FAILED: flake8 style check; begin output

./cusignal/test/test_filtering.py:547:5: F811 redefinition of unused 'TestFirfilter' from line 501

./cusignal/filtering/filtering.py:174:41: E127 continuation line over-indented for visual indent

./cusignal/filtering/filtering.py:177:53: E127 continuation line over-indented for visual indent

./cusignal/filtering/filtering.py:398:1: E305 expected 2 blank lines after class or function definition, found 1

./cusignal/filtering/filtering.py:398:1: E402 module level import not at top of file

./cusignal/filtering/filtering.py:398:1: F401 'scipy.signal as sig' imported but unused

./cusignal/filtering/filtering.py:400:1: E302 expected 2 blank lines, found 1

>>>> FAILED: flake8 style check; end output
```

2020-12-04 14:09 UTC, awthomp commented
rerun tests

2020-12-04 20:42 UTC, luigifcruz commented
I think the CI is installing the wrong version of Cupy. This PR requires `cupy>=9.0.0a1`. I'm not sure if I can change this. :laughing:

2020-12-04 20:44 UTC, awthomp reviewed
> I think the CI is installing the wrong version of Cupy. This PR requires `cupy>=9.0.0a1`. I'm not sure if I can change this. 😆

I'll fix this, @luigifcruz !

2020-12-04 20:48 UTC, luigifcruz commented on python/cusignal/filter_design/fir_filter_design.py
> +    return out
Yes we can. I did this way because Cupy was a bit slower than Numpy. I will implement `gpumode` alongside with `cpumode`.

2020-12-04 20:50 UTC, awthomp commented on python/cusignal/filter_design/fir_filter_design.py
> +    return out
I'll profile both too, and we can ultimately roll in whatever is faster. After merging in this code, we can look to optimize via custom CUDA kernels. I follow the "lets get high performance features to the public as fast as possible" and then "optimize for best perf later" montra :).

2020-12-14 13:39 UTC, awthomp commented
Hey @luigifcruz -- as a heads up, I'm still trying to figure out how to bump the cupy version and not break CI/CD for the other RAPIDS projects. Discussion here: https://github.com/rapidsai/cusignal/pull/292

2020-12-14 16:53 UTC, luigifcruz commented
Thanks, @awthomp! No hurry, the stable release of Cupy version 9.0.0 is meant to be released just in April.

2021-01-06 15:42 UTC, awthomp commented
> Thanks, @awthomp! No hurry, the stable release of Cupy version 9.0.0 is meant to be released just in April. It's a shame we need to wait this long for a simple method.

Totally agree, @luigifcruz. The issue is more in how we do packaging than anything else. I'm going to sit on this PR until 9.0 is available via conda (whether a nightly release or not). Looks good, initially. I want to do some V100 and A100 testing at scale to see if we can GPU accelerate more of the internals.

I'm watching this for CuPy 9.0: https://anaconda.org/search?q=cupy

2021-02-17 13:20 UTC, awthomp commented
rerun tests

2021-03-04 15:26 UTC, awthomp commented
rerun tests

2021-03-05 18:02 UTC, ajschmidt8 requested changes
There is currently some discussion about upgrading to CuPy 9 for the other RAPIDS libraries happening on the PR below. I will temporarily request changes on this PR to prevent any accidental merges before that PR is resolved/merged.


https://github.com/rapidsai/integration/pull/205

2021-04-22 15:32 UTC, luigifcruz commented
Great news, CuPy v9.0 was just released! https://github.com/cupy/cupy/releases/v9.0.0

2021-04-22 15:34 UTC, awthomp commented
> Great news, CuPy v9.0 was just released! https://github.com/cupy/cupy/releases/v9.0.0

Yes! Hopefully CI/CD pulls in 9.0, and we can get this PR merged. Thanks for your patience, Luigi!

2021-04-27 23:45 UTC, awthomp commented
rerun tests

2021-04-27 23:48 UTC, awthomp commented
@luigifcruz We just enabled support with CuPy 9: https://github.com/rapidsai/cusignal/pull/359

I'll re-run CI today and then in the morning. I'm not totally sure how we update our conda packages (e.g. if this PR is immediate or we need to wait until a new build this evening), but I'll rerun tests again in the morning. Looking like we can get this merged soon.

2021-04-28 14:57 UTC, awthomp commented
@ajschmidt8 -- It looks like CI tests for cusignal are still on CuPy 8.6, which is causing tests in this PR to fail. Is there anyway to force CI to pull CuPy 9.0? Looks like we're passing our builds now, though... 🤔

2021-04-28 15:03 UTC, ajschmidt8 commented
@awthomp, the containers won't have `cupy v9` until [this integration PR](https://github.com/rapidsai/integration/pull/205) and the associated PRs [here](https://github.com/rapidsai/integration/pull/205#issuecomment-827751956) are all merged. Looks like we're just waiting on https://github.com/rapidsai/cudf/pull/8082 at this point. Once that PR is merged, we can merge the `integration` PR and then all of our build/test containers will be updated to `cupy v9` and we can rerun the tests here.

2021-04-28 16:17 UTC, awthomp commented
@luigifcruz -- Could you resubmit this PR to branch-0.20? Looks like CI will pass here in the next few days.

2021-04-28 19:52 UTC, ajschmidt8 commented
> @luigifcruz -- Could you resubmit this PR to branch-0.20? Looks like CI will pass here in the next few days.

I updated the base branch in this PR to target `branch-0.20`. should be all set now.

2021-04-28 19:53 UTC, awthomp commented
Thanks, @ajschmidt8 !

2021-04-28 22:44 UTC, jakirkham commented
rerun tests

(now that PR https://github.com/rapidsai/integration/pull/205 is merged :)

2021-04-29 13:40 UTC, awthomp commented
rerun tests

2021-04-29 15:16 UTC, ajschmidt8 commented
looks like the failing checks here are leftover from the previous branch. the current checks for this branch did pass though. I'll approve this PR. @awthomp, I'll leave it to you for a final review and merge.

2021-04-29 15:16 UTC, ajschmidt8 approved these changes

2021-04-29 16:14 UTC, awthomp commented
@luigifcruz -- I know it's been awhile since you've submitted this PR, and we all thank you for your patience. Before we merge, was there anything else you wanted to include here w/ CuPy 9.0?

2021-04-29 16:30 UTC, luigifcruz commented
@awthomp -- Thanks for taking the time to review this PR! I have nothing to add at this moment.

2021-04-29 16:31 UTC, awthomp approved these changes

2021-04-29 16:31 UTC, awthomp commented
@gpucibot merge

2021-04-29 16:32 UTC, merged