mvdr perf optimizations and addition of elementwise divide kernel
rapidsai/cusignal pull request #403
Opened 2021-07-19 20:03 UTC by awthomp

Previous version of mvdr beamformer failed to account for the fact that the `wA` denominator result is a scalar. Removing inverse and additional matmul in addition to adding elementwise kernel

2021-07-19 20:05 UTC, awthomp commented
@mnicely -- Mind looking at this perf improvement? Particularly the elementwise kernel?

2021-07-19 20:16 UTC, mnicely commented
Can you request an official review? At airport, it'll be easier on phone.

2021-07-19 20:17 UTC, awthomp commented
> Can you request an official review? At airport, it'll be easier on phone.

Done

2021-07-19 20:19 UTC, mnicely requested changes
No need to use EWK. Just use "/" and CuPy will kick off the divide kernel.

2021-07-19 20:21 UTC, awthomp commented
> No need to use EWK. Just use "/" and CuPy will kick off the divide kernel.

Removed. I thought I'd get to improve on some overhead :).

2021-07-19 20:32 UTC, mnicely requested changes
I think you left off the inverse...

2021-07-19 20:33 UTC, awthomp commented
> I think you left off the inverse...

Don't need it. wA collapses to a scalar (which we missed in the initial implementation), so you can do a simple divide rather than a multiply with an inverse.

2021-07-19 20:34 UTC, mnicely approved these changes
Gotcha!

2021-07-19 22:01 UTC, awthomp commented
@gpucibot merge

2021-07-19 22:01 UTC, awthomp commented
rerun tests

2021-07-20 14:08 UTC, awthomp commented
rerun tests

2021-07-20 19:53 UTC, awthomp commented
rerun tests

2021-07-20 20:29 UTC, awthomp commented
@gpucibot merge

2021-07-20 20:29 UTC, merged