Speedup: Single-precision hilbert, resample, and lfilter_zi.
rapidsai/cusignal pull request #447
Opened 2022-01-06 03:57 UTC by luigifcruz

Hi!

I noticed some functions weren't respecting the input type and thus returning double precision results.

This pull request proposes two changes:

1. Make `resample` return a buffer with the same `dtype` as input.
2. Add single-precision `hilbert` and `hilbert2` kernels.

I also benchmarked each change:

1. Upstream: **471 µs** vs. Proposed: **260 µs**
2. Upstream: **1.47 ms** vs. Proposed: **610 µs**

2022-01-06 12:12 UTC, mnicely commented
Hi @luigifcruz
Good catch on data type.
I'll get back to you soon with a review, I think there might be a simpler solution.

2022-01-06 13:07 UTC, mnicely requested changes
Can you please type specific tests as well, in `test_filtering.py`

```python
    @pytest.mark.benchmark(group="Hilbert")
    @pytest.mark.parametrize("dtype", [np.float32, np.float64])
    @pytest.mark.parametrize("dim, num_samps", [(1, 2 ** 15), (2, 2 ** 8)])
    class TestHilbert:
...
```

2022-01-06 13:07 UTC, mnicely commented on python/cusignal/filtering/filtering.py
> +_hilbert_kernel = {
I like the convention, but it can be pretty verbose. Let's utilize typecasting by changing `float64` to `T`.

2022-01-06 13:07 UTC, mnicely commented on python/cusignal/filtering/filtering.py
> +    if Xf.dtype.char is "F":
By using deduction, we no longer need this check.

We instead allocate an empty array for h, like
`h = cp.empty((N,), dtype=x.dtype)`

2022-01-06 13:07 UTC, mnicely commented on python/cusignal/filtering/resample.py
> +    Y = cp.zeros(newshape, dtype=X.dtype)
LGTM

2022-01-06 13:09 UTC, mnicely commented on python/cusignal/filtering/filtering.py
> +    if Xf.dtype.char is "F":
I forgot to mention, now that we have `h` allocated, we only need the following

`_hilbert_kernel(h)`
and
`_hilbert2_kernel(h1, h2)`

2022-01-06 13:36 UTC, awthomp commented
Thanks for the PR @luigifcruz! Once you make these suggested changes from @mnicely, we'll merge. I changed the merge target branch to `branch-22.02` instead of `main` and added some CI flags to get all checks to clear. I still think we'll have a style change, but Matt may have pointed that out too.

2022-01-10 19:59 UTC, ajschmidt8 approved these changes
Approving `ops-codeowner` file changes

2022-01-15 04:26 UTC, luigifcruz commented
Thanks for the feedback @mnicely & @awthomp!

I implemented the requested style changes with 9d6d7aaceaf0f793d2d73ec0ccab8269faffe60b and type check tests with bc9dcd9750c182f02dfa488b12d2cc745b6c9063. I had to patch the `linspace_data_gen` function to accept a optional `dtype` argument with 279fe01d22b492c8aa7fe4c410db61523f54896f. I also had to increase the tolerances of the `array_equal` method for single-precision arrays with 7ea86f658b7dd7f948417eedf608f9fff578931b. This patch is required to successfully pass all tests. I believe this is caused by Scipy using double-precision arrays. I [submitted](https://github.com/scipy/scipy/pull/15366) a PR to Scipy but the fix should be available only with `scipy>=1.9.0`. You guys might want to handle the tolerances in a different way than I implemented.

I also noticed that the `lfilter_zi` method was returning a double-precision array no matter the input type. This would result in the `filtfilt` method always retuning a double-precision value. The patches for this are found in b5000ef6661dbc383f0831c441339d43143c8c13.

2022-01-18 01:47 UTC, awthomp approved these changes

2022-01-18 01:48 UTC, awthomp commented
@mnicely -- I don't think we can merge until you sign off on @luigifcruz 's fixes. Can you give this a look? 

Looks great, Luigi. You're the best! Thanks, as always, for contributing.

2022-01-18 15:30 UTC, mnicely approved these changes

2022-01-18 15:31 UTC, awthomp commented
@gpucibot merge

2022-01-18 15:31 UTC, merged

2022-01-18 18:21 UTC, luigifcruz commented
Awesome, @awthomp! Thanks all for maintaining this awesome project!